# Generated by Django 5.1.4 on 2024-12-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Award Name')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Award Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/', verbose_name='Award Image')),
                ('count', models.IntegerField(verbose_name='Award Count')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='Full Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='User Image')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='YearOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Year Order',
                'verbose_name_plural': 'Year Orders',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='AwardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100, verbose_name='Order Type')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_orders', to='api.award', verbose_name='Award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_orders', to='api.user', verbose_name='Recipient')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_orders', to='api.yearorder', verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Award Order',
                'verbose_name_plural': 'Award Orders',
                'ordering': ['year', 'award'],
            },
        ),
    ]
