# Generated by Django 5.1.4 on 2024-12-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardorder',
            name='award',
        ),
        migrations.RemoveField(
            model_name='awardorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='awardorder',
            name='year',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='AwardOrder',
        ),
        migrations.DeleteModel(
            name='YearOrder',
        ),
    ]
