# Generated by Django 5.1.4 on 2024-12-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_awardorder_award_remove_awardorder_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='Full Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='User Image')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['fio'],
            },
        ),
    ]
