# Generated by Django 5.1.4 on 2024-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentDecree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_president_decree', models.IntegerField(verbose_name='Number president decree')),
                ('year', models.DateField(verbose_name='Year date')),
            ],
            options={
                'verbose_name': 'Year Order',
                'verbose_name_plural': 'Year Orders',
                'ordering': ['year'],
            },
        ),
    ]
