# Generated by Django 5.1.4 on 2024-12-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_presidentdecree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presidentdecree',
            options={'ordering': ['year'], 'verbose_name': 'Presiden Decree', 'verbose_name_plural': 'President Decrees'},
        ),
        migrations.CreateModel(
            name='AwardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100, verbose_name='Order Type')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_orders', to='api.award', verbose_name='Award')),
                ('number_president_decree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_orders', to='api.presidentdecree', verbose_name='Number decree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_orders', to='api.user', verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Award Order',
                'verbose_name_plural': 'Award Orders',
                'ordering': ['number_president_decree', 'award'],
            },
        ),
    ]
